-- MySQL Script generated by MySQL Workbench
-- Sat Mar  6 16:14:03 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema info_team08_schema
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema info_team08_schema
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `info_team08_schema` DEFAULT CHARACTER SET utf8 ;
USE `info_team08_schema` ;

-- -----------------------------------------------------
-- Table `info_team08_schema`.`Playlist`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `info_team08_schema`.`Playlist` ;

CREATE TABLE IF NOT EXISTS `info_team08_schema`.`Playlist` (
  `idPlaylist` INT NOT NULL AUTO_INCREMENT,
  `nomPlaylist` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idPlaylist`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `info_team08_schema`.`Genre`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `info_team08_schema`.`Genre` ;

CREATE TABLE IF NOT EXISTS `info_team08_schema`.`Genre` (
  `idGenre` INT NOT NULL,
  `nomGenre` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idGenre`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `info_team08_schema`.`Client`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `info_team08_schema`.`Client` ;

CREATE TABLE IF NOT EXISTS `info_team08_schema`.`Client` (
  `mail` VARCHAR(45) NOT NULL,
  `password` VARCHAR(45) NOT NULL,
  `civilite` VARCHAR(45) NOT NULL,
  `nom` VARCHAR(45) NOT NULL,
  `prenom` VARCHAR(45) NOT NULL,
  `dateNaissance` DATE NOT NULL,
  `adresseFacturation` VARCHAR(45) NOT NULL,
  `Playlist_idPlaylist` INT NOT NULL,
  `nbEcoute` INT NULL,
  `styleMusiquePrefere` INT NOT NULL,
  PRIMARY KEY (`mail`, `password`),
  INDEX `fk_Client_Playlist1_idx` (`Playlist_idPlaylist` ASC),
  INDEX `fk_Client_Genre1_idx` (`styleMusiquePrefere` ASC),
  CONSTRAINT `fk_Client_Playlist1`
    FOREIGN KEY (`Playlist_idPlaylist`)
    REFERENCES `info_team08_schema`.`Playlist` (`idPlaylist`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_Client_Genre1`
    FOREIGN KEY (`styleMusiquePrefere`)
    REFERENCES `info_team08_schema`.`Genre` (`idGenre`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `info_team08_schema`.`ElementCatalogue`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `info_team08_schema`.`ElementCatalogue` ;

CREATE TABLE IF NOT EXISTS `info_team08_schema`.`ElementCatalogue` (
  `idCatalogue` INT NOT NULL AUTO_INCREMENT,
  `nbEcoute` INT NULL,
  `recommande` TINYINT NULL,
  PRIMARY KEY (`idCatalogue`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `info_team08_schema`.`TitreMusical`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `info_team08_schema`.`TitreMusical` ;

CREATE TABLE IF NOT EXISTS `info_team08_schema`.`TitreMusical` (
  `idCatalogue` INT NOT NULL AUTO_INCREMENT,
  `titre` VARCHAR(45) NOT NULL,
  `idInterprete` INT NOT NULL,
  `dateCreation` DATE NOT NULL,
  `duree` INT NULL,
  `idGenre` INT NOT NULL,
  PRIMARY KEY (`idCatalogue`),
  INDEX `fk_TitreMusical_Genre1_idx` (`idGenre` ASC),
  CONSTRAINT `fk_TitreMusical_Catalogue1`
    FOREIGN KEY (`idCatalogue`)
    REFERENCES `info_team08_schema`.`ElementCatalogue` (`idCatalogue`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_TitreMusical_Genre1`
    FOREIGN KEY (`idGenre`)
    REFERENCES `info_team08_schema`.`Genre` (`idGenre`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `info_team08_schema`.`Album`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `info_team08_schema`.`Album` ;

CREATE TABLE IF NOT EXISTS `info_team08_schema`.`Album` (
  `idCatalogue` INT NOT NULL,
  `nom` VARCHAR(45) NOT NULL,
  `idInterprete` INT NOT NULL,
  `dateSortie` DATE NOT NULL,
  `duree` INT NULL,
  `idTitreMusical` INT NOT NULL,
  PRIMARY KEY (`idCatalogue`),
  CONSTRAINT `fk_Album_Catalogue1`
    FOREIGN KEY (`idCatalogue`)
    REFERENCES `info_team08_schema`.`ElementCatalogue` (`idCatalogue`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `info_team08_schema`.`Podcast`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `info_team08_schema`.`Podcast` ;

CREATE TABLE IF NOT EXISTS `info_team08_schema`.`Podcast` (
  `idCatalogue` INT NOT NULL,
  `titre` VARCHAR(45) NOT NULL,
  `duree` INT NOT NULL,
  `pseudoAuteur` VARCHAR(45) NOT NULL,
  `categorie` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idCatalogue`),
  CONSTRAINT `fk_Podcast_Catalogue1`
    FOREIGN KEY (`idCatalogue`)
    REFERENCES `info_team08_schema`.`ElementCatalogue` (`idCatalogue`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `info_team08_schema`.`Radio`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `info_team08_schema`.`Radio` ;

CREATE TABLE IF NOT EXISTS `info_team08_schema`.`Radio` (
  `idCatalogue` INT NOT NULL,
  `nom` VARCHAR(45) NOT NULL,
  `genre` INT NOT NULL,
  PRIMARY KEY (`idCatalogue`),
  INDEX `fk_Radio_Genre1_idx` (`genre` ASC),
  CONSTRAINT `fk_Radio_Catalogue1`
    FOREIGN KEY (`idCatalogue`)
    REFERENCES `info_team08_schema`.`ElementCatalogue` (`idCatalogue`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_Radio_Genre1`
    FOREIGN KEY (`genre`)
    REFERENCES `info_team08_schema`.`Genre` (`idGenre`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `info_team08_schema`.`Interprete`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `info_team08_schema`.`Interprete` ;

CREATE TABLE IF NOT EXISTS `info_team08_schema`.`Interprete` (
  `idInterprete` INT NOT NULL AUTO_INCREMENT,
  `pseudonyme` VARCHAR(45) NOT NULL,
  `prenom` VARCHAR(45) NULL,
  `nom` VARCHAR(45) NULL,
  `dateNaissance` DATE NULL,
  PRIMARY KEY (`idInterprete`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `info_team08_schema`.`Administrateur`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `info_team08_schema`.`Administrateur` ;

CREATE TABLE IF NOT EXISTS `info_team08_schema`.`Administrateur` (
  `mail` VARCHAR(45) NOT NULL,
  `password` VARCHAR(45) NOT NULL,
  `profilGestionClient` TINYINT NULL,
  `profilGestionMusique` TINYINT NULL,
  PRIMARY KEY (`mail`, `password`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `info_team08_schema`.`ElementsPlaylist`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `info_team08_schema`.`ElementsPlaylist` ;

CREATE TABLE IF NOT EXISTS `info_team08_schema`.`ElementsPlaylist` (
  `Playlist_idPlaylist` INT NOT NULL,
  `Catalogue_idCatalogue` INT NOT NULL,
  PRIMARY KEY (`Playlist_idPlaylist`, `Catalogue_idCatalogue`),
  INDEX `fk_Playlist_has_Catalogue_Catalogue1_idx` (`Catalogue_idCatalogue` ASC),
  INDEX `fk_Playlist_has_Catalogue_Playlist1_idx` (`Playlist_idPlaylist` ASC),
  CONSTRAINT `fk_Playlist_has_Catalogue_Playlist1`
    FOREIGN KEY (`Playlist_idPlaylist`)
    REFERENCES `info_team08_schema`.`Playlist` (`idPlaylist`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_Playlist_has_Catalogue_Catalogue1`
    FOREIGN KEY (`Catalogue_idCatalogue`)
    REFERENCES `info_team08_schema`.`ElementCatalogue` (`idCatalogue`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `info_team08_schema`.`Discographie`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `info_team08_schema`.`Discographie` ;

CREATE TABLE IF NOT EXISTS `info_team08_schema`.`Discographie` (
  `Interprete_idInterprete` INT NOT NULL,
  `TitreMusical_Catalogue_idCatalogue` INT NOT NULL,
  PRIMARY KEY (`Interprete_idInterprete`, `TitreMusical_Catalogue_idCatalogue`),
  INDEX `fk_Interprete_has_TitreMusical_TitreMusical1_idx` (`TitreMusical_Catalogue_idCatalogue` ASC),
  INDEX `fk_Interprete_has_TitreMusical_Interprete1_idx` (`Interprete_idInterprete` ASC),
  CONSTRAINT `fk_Interprete_has_TitreMusical_Interprete1`
    FOREIGN KEY (`Interprete_idInterprete`)
    REFERENCES `info_team08_schema`.`Interprete` (`idInterprete`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_Interprete_has_TitreMusical_TitreMusical1`
    FOREIGN KEY (`TitreMusical_Catalogue_idCatalogue`)
    REFERENCES `info_team08_schema`.`TitreMusical` (`idCatalogue`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `info_team08_schema`.`AlbumInterprete`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `info_team08_schema`.`AlbumInterprete` ;

CREATE TABLE IF NOT EXISTS `info_team08_schema`.`AlbumInterprete` (
  `Album_Catalogue_idCatalogue` INT NOT NULL,
  `Interprete_idInterprete` INT NOT NULL,
  PRIMARY KEY (`Album_Catalogue_idCatalogue`, `Interprete_idInterprete`),
  INDEX `fk_Album_has_Interprete_Interprete1_idx` (`Interprete_idInterprete` ASC),
  INDEX `fk_Album_has_Interprete_Album1_idx` (`Album_Catalogue_idCatalogue` ASC),
  CONSTRAINT `fk_Album_has_Interprete_Album1`
    FOREIGN KEY (`Album_Catalogue_idCatalogue`)
    REFERENCES `info_team08_schema`.`Album` (`idCatalogue`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_Album_has_Interprete_Interprete1`
    FOREIGN KEY (`Interprete_idInterprete`)
    REFERENCES `info_team08_schema`.`Interprete` (`idInterprete`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;

USE `info_team08_schema` ;

-- -----------------------------------------------------
-- procedure nouveau_admin
-- -----------------------------------------------------

USE `info_team08_schema`;
DROP procedure IF EXISTS `info_team08_schema`.`nouveau_admin`;

DELIMITER $$
USE `info_team08_schema`$$
CREATE PROCEDURE `nouveau_admin` (mail VARCHAR(45), password VARCHAR(45), gestionClient BOOL, gestionMusique BOOL)
BEGIN
	INSERT INTO `info_team08_schema`.`Administrateur` (`mail`, `password`, `profilGestionClient`, `profilGestionMusique`) VALUES (mail, password, gestionClient, gestionMusique);
END$$

DELIMITER ;

-- -----------------------------------------------------
-- procedure nouveau_client
-- -----------------------------------------------------

USE `info_team08_schema`;
DROP procedure IF EXISTS `info_team08_schema`.`nouveau_client`;

DELIMITER $$
USE `info_team08_schema`$$
CREATE PROCEDURE `nouveau_client` (mail VARCHAR(45), password VARCHAR(45), civilite VARCHAR(45), nom VARCHAR(45), prenom VARCHAR(45), dateNaissance DATE, adresseFacturation VARCHAR(45), styleMusique INT)
BEGIN
	INSERT INTO `info_team08_schema`.`Client` (`mail`, `password`, `civilite`, `nom`, `prenom`, `dateNaissance`, `adresseFacturation`, `styleMusiquePrefere`) 
										VALUES (mail, password, civilite, nom, prenom, dateNaissance, adresseFacturation, styleMusique);
END$$

DELIMITER ;

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
